### ISSUE TITLE
Street address search displays different address in position bar in some cases

### ISSUE THREAD

**Issue by tituomin** [nordsoftware/outdoors-sports-map#16]
Because the position coordinates are always reverse geocoded again in the servicemap API even if they are the result of street address geocoding in the HSL API, the resulting street address always almost differs from the original... Example: Mannerheimintie 5. Would it be difficult to reuse the original street address in the cases?

**Comment by jonnetanninen** [comment]
This is very hard to accomplish at this point as the search result formats from the API differ significantly.

**Comment by hugovk** [comment]
This repo is now archived, if this is still relevant please report to https://github.com/City-of-Helsinki/outdoors-sports-map.
