### ISSUE TITLE
Fetch and store services separately to make fetching units faster

### ISSUE THREAD

**Issue by vaaralav** [nordsoftware/outdoors-sports-map#18]

**Comment by vaaralav** [comment]
After investigating this issue it seems that removing `include=services` doesn't make the request remarkably faster. Removing `include=observations` however reduces the response time from ~7s to ~2.5s.

**Comment by tituomin** [comment]
Now an optimized API version is deployed. The include=services part is hard to optimize and currently incurs about 500 ms more to the request. (Maybe not critical.) Optimizing geometries and observations in the backend code approximately halved the request time.
