### ISSUE TITLE
Add Open Graph and search engine friendly meta tags

### ISSUE THREAD

**Issue by terotik** [nordsoftware/outdoors-sports-map#49]
Make search engine results and social media share previews comprehensible.

![screen shot 2017-04-28 at 10 33 14](https://cloud.githubusercontent.com/assets/664877/25518929/69ad7524-2bfe-11e7-9248-c0928a22f24e.png)

**Comment by hugovk** [comment]
This repo is now archived, if this is still relevant please report to https://github.com/City-of-Helsinki/outdoors-sports-map.
