### ISSUE TITLE
Handle notice observations with empty payload

### ISSUE THREAD

**Issue by vaaralav** [nordsoftware/outdoors-sports-map#52]
SingleUnitModal should have a check if the notice observation actually has some value and show the notice box only when there's a non-empty value.

See the Notice box in the screen shot and the warning below:

<img width="395" alt="screen shot 2017-05-28 at 09 58 09" src="https://cloud.githubusercontent.com/assets/8571541/26525776/3c9a825c-438c-11e7-96a1-fe75e5f99d1c.png">

```
Warning: Failed prop type: The prop `source` is marked as required in `ReactMarkdown`, but its value is `null`.
    in ReactMarkdown (created by NoticeInfo)
    in NoticeInfo (created by SingleUnitModalContainer)
    in div (created by ModalBody)
    in ModalBody (created by SingleUnitModalContainer)
    in div (created by ModalDialog)
    in div (created by ModalDialog)
    in div (created by ModalDialog)
    in ModalDialog (created by Modal)
    in div (created by Modal)
```

**Comment by hugovk** [comment]
This repo is now archived, if this is still relevant please report to https://github.com/City-of-Helsinki/outdoors-sports-map.
