### ISSUE TITLE
This should also be translated, because the temperature string contains words like "yli" = "över" = "over". The translations are already available in the API.

### ISSUE THREAD

**Issue by tituomin** [nordsoftware/outdoors-sports-map#59]
https://github.com/digiaonline/outdoors-sports-map/blob/fcc2edd40fb20d969e9ec3c983254cef70bec768/src/modules/unit/components/SingleUnitModalContainer.js#L158

**Comment by hugovk** [comment]
This repo is now archived, if this is still relevant please report to https://github.com/City-of-Helsinki/outdoors-sports-map.
